### ISSUE TITLE
Doing a full initial sync will miss some dependencies

### ISSUE THREAD

**Issue by dpiddy** [bundler/bundler-api#10]
Due to [this condition](https://github.com/rubygems/bundler-api/blob/0d869ffd14c2031e1e542e84e094583476aaa2d0/lib/bundler_api/update/job.rb#L111) an initial sync will miss dependencies on gems that have not been synced yet.

For example, version 3.0.1 of the aasm gem depends on activerecord. Since the sync is done in seemingly alphabetical order, when version 3.0.1 of aasm is synced its dependency on activerecord will not be recorded since that gem has not been synced yet.

Guessing bundler-api as deployed to bundler-api.herokuapp.com was seeded with data extracted from rubygems.org so it skipped this step.

**Comment by indirect** [comment]
Closing as solved by the catch-up rake task for now.
