### ISSUE TITLE
Expire Fastly cache on new index files

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-api#132]
Today, we tell Fastly to cache compact index files for a very long time, via HTTP headers:

> Surrogate-Control: max-age=2592000, stale-while-revalidate=60

We need to tell Fastly when the cache is invalidated (by, say, a new gem being released), so that it will re-fetch an up-to-date version of the file. Resolving this should also fix bundler/bundler#4371.

**Comment by TimMoore** [comment]
https://docs.fastly.com/guides/purging/single-purges.html#purging-with-a-key
https://docs.fastly.com/api/purge

**Comment by dwradcliffe** [comment]
Yeah we should do this with a surrogate key, such as `new-index`, like we do with the full index files.

For reference:
https://github.com/rubygems/rubygems.org/blob/071df7d625ee18be64d225e78abb445fdbf17462/app/jobs/indexer.rb#L60
https://github.com/rubygems/rubygems.org/blob/071df7d625ee18be64d225e78abb445fdbf17462/app/jobs/indexer.rb#L46
https://github.com/rubygems/rubygems.org/blob/071df7d625ee18be64d225e78abb445fdbf17462/lib/fastly.rb

**Comment by TimMoore** [comment]
I think we might want to be more fine-grained than that, however. Pushing a gem shouldn't expire the cache for other gems' info files, correct?

**Comment by indirect** [comment]
Yeah, we should be able to expire only the `/info/NAME` file for the gem in question and the main `/versions` file.

**Comment by indirect** [comment]
We also need to expire `/names` if there's never been a gem with that name before. h/t @segiddins
