### ISSUE TITLE
Check for cache compliance with the caching RFC

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler-api#154]
The relevant cache line: https://github.com/bundler/bundler-api/blob/2cbbd3df69bce6cdec3c1cf9ad8a6bfe9b4a8cd5/lib/bundler_api/web.rb#L211

RFC: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by indirect** [comment]
I checked this and it appears to be set correctly at the source and from Fastly 👍
