### ISSUE TITLE
[Wishlist] Differentiate type of dependency

### ISSUE THREAD

**Issue by balasankarc** [bundler/bundler-api#155]
Right now, the first entry on http://bundler.rubygems.org/api/v1/dependencies.json?gems=rexical  lists `hoe` as a dependency.  But, we can't know if that is a Development Dependency (which it is) or a Runtime Dependency. It would be great to have that information too.

PS : We are planning to use this API for our [Debian Packaging progressbar](http://debian.fosscommunity.in/status/gitlab) to get dependency information and we intend to prioritize Runtime dependencies over development dependencies. And, getting this information from the API would be a great help

**Comment by segiddins** [comment]
It's unlikely we'll be adding more to the dependency API -- it's purposefully kinda single purpose. If you need this info, you'll either need to download the full index or use other RubyGems APIs, I think.

**Comment by balasankarc** [comment]
Ok Then. Let me try some other way. :)
