### ISSUE TITLE
Enable configuration for an enterprise private gem server

### ISSUE THREAD

**Issue by TiagoCardoso1983** [bundler/bundler-api#171]
We have this local gem server in our enterprise for private company projects. Until very recently we were using geminabox, which kinda-sorta implements bundler API, and we lived with the performance issues and lack of AAA features.

We have just started migrating most of the service supply to the web server (Apache) itself, in that the gems are served directly from it, and the push/ endpoint is now served using a ruby cgi script, which will perform some ldap/authorization validations before uploading the gem and reindexing. With that, we have effectively migrated the Rubygems API. 

However, the bundler API support is gone, which is no significant problem with bundler 1.x, as it falls back to Rubygems API. It would be nice to have it though. I was wondering whether the endpoint could be also easily cgi-scripted, in that we could just mirror what we did with the rubygems endpoints, and the bundler-api gem would just provide the necessary public APi around it. It seems that this is just proxying to rubygems, but is there a way to configure it with an internal endpoint?

Thx anyway for any sort of reply. I understand this is not an issue and will not be offend if it's project policy to just close it and redirect me to a proper debate forum like a google group or anything similar.

**Comment by segiddins** [comment]
Take a look at the gemstash project, it's our official answer for running private gem servers / mirrors

**Comment by TiagoCardoso1983** [comment]
@segiddins thx, gemstash looks indeed like a more completed solution than geminabox.

I would like a way to use it under a cgi environment though. Reasons would be costumization for AAA, better memory footprint (Apache/CGI instead of long running unicorns/pumas) and a smaller stack to support (did I misunderstand or does gemstash requires memcached?). 

I saw that @gem_source object being used directly in most of the endpoints (under web.rb). is that part of some rack middleware or could I use it directly as a decoupled object which would handle all the logic for me and I'd just just have to build the AAA around it?

**Comment by indirect** [comment]
@TiagoCardoso1983 Ruby web frameworks cannot run under CGI. I recommend that you give up on that idea right now, sorry.

This project does not know how to act as a gem server. It only knows how to serve the dependency API, and it depends on Postgresql, Memcached, and Redis.

Gemstash defaults to using Sqlite3, does not require Memcached, and does not require Redis.
