### ISSUE TITLE
Place nicely with foreman

### ISSUE THREAD

**Issue by lmarburger** [bundler/bundler-api#41]
We're using dotenv to manage the environment loaded from `.env` and `.env.local`. dotenv will ignore setting an environment variable if it exists. foreman will load `.env` itself when starting a process or running a command. Any environment overrides in `.env.local` will have no effect when the app boots and dotenv loads it because all the values it overrides will already be defined.

For example, set `MAX_THREADS` in both `.env` and `.env.local`. The value in `.env` will be used when starting the site using `foreman start web` whereas the value from `.env.local` will be used when using `script/web`.

One solution is to submit a patch to dotenv that changes the behavior to override instead of ignore existing environment variables.

**Comment by indirect** [comment]
Closing this as fixed in foreman.
