### ISSUE TITLE
Exception when gems is an array

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-api#50]
Error detected in: Bundler API ()

Full report at https://www.honeybadger.io/inspector/p/349/4426817

NoMethodError: undefined method `split' for ["rails"]:Array

Summary

http://bundler.rubygems.org/api/v1/dependencies?gems[]=rails
Trace

/app/lib/bundler_api/web.rb:48:in `gems`
/app/lib/bundler_api/web.rb:53:in `get_deps`
/app/lib/bundler_api/web.rb:98:in `block in <class:Web>`

**Comment by andremedeiros** [comment]
@indirect can I close this one? I think you've fixed it with 9c08ea94d8e6ab632741f4a92177aa1752fd33c1.

**Comment by indirect** [comment]
Yup, thanks!
