### ISSUE TITLE
Vagrant file?

### ISSUE THREAD

**Issue by fotanus** [bundler/bundler-api#76]
Hello,

Are you guys interested in a vagrant file? I can provide it.

**Comment by indirect** [comment]
Right now (if you have Ruby installed) setup should just be `bundle install`. Is Vagrant needed for more than that?

**Comment by fotanus** [comment]
There is also the usual needs like databasem redis and memcached

**Comment by indirect** [comment]
Ah, right.  I'm not sure how many people use Vagrant to work on this, but offering the option seems good. Send the PR, please. :)

**Comment by RochesterinNYC** [comment]
Is this something we're still interested in?

**Comment by indirect** [comment]
Maybe, I guess? None of the current maintainers use Vagrant, so I'm worried that this adds to the maintenance burden without actually helping many people.

**Comment by RochesterinNYC** [comment]
Okay, that's fair. Might be a solution to a non-existent pain point at the moment. We can close this issue then?

**Comment by fotanus** [comment]
Right, lets close this!
